/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISeeder, ISeederInterface } from "../ISeeder";

const _abi = [
  {
    inputs: [],
    name: "generateSeed",
    outputs: [
      {
        components: [
          {
            internalType: "uint48",
            name: "head",
            type: "uint48",
          },
          {
            internalType: "uint48",
            name: "body",
            type: "uint48",
          },
        ],
        internalType: "struct ISeeder.Seed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISeeder__factory {
  static readonly abi = _abi;
  static createInterface(): ISeederInterface {
    return new utils.Interface(_abi) as ISeederInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISeeder {
    return new Contract(address, _abi, signerOrProvider) as ISeeder;
  }
}
